package com.example.core.source.mapper

import com.example.core.domain.model.FoodDetail
import com.example.core.source.db.remote.response.FoodDetailItemResponse
import com.example.foodappdagger.core.data.mapper.BaseMapper

class DetailMapper :BaseMapper<FoodDetailItemResponse,FoodDetail> {
    override fun mapToDomain(model: FoodDetailItemResponse): FoodDetail {
        return FoodDetail(

            model.dateModified,
            model.idMeal,
            model.strCategory,
            model.strMealThumb,
            model.strArea,
            model.strCreativeCommonsConfirmed,
            model.strImageSource,
            model.strInstructions,
            model.strTags,
            model.strYoutube,
            model.strDrinkAlternate,
            model.strSource,
            model.strMeal,

            model.strIngredient1,
            model.strIngredient2,
            model.strIngredient3,
            model.strIngredient4,
            model.strIngredient5,
            model.strIngredient6,
            model.strIngredient7,
            model.strIngredient8,
            model.strIngredient9,
            model.strIngredient10,
            model.strIngredient11,
            model.strIngredient12,
            model.strIngredient13,
            model.strIngredient14,
            model.strIngredient15,
            model.strIngredient16,
            model.strIngredient17,
            model.strIngredient18,
            model.strIngredient19,
            model.strIngredient20,

            model.strMeasure1,
            model.strMeasure2,
            model.strMeasure3,
            model.strMeasure4,
            model.strMeasure5,
            model.strMeasure6,
            model.strMeasure7,
            model.strMeasure8,
            model.strMeasure9,
            model.strMeasure10,
            model.strMeasure11,
            model.strMeasure12,
            model.strMeasure13,
            model.strMeasure14,
            model.strMeasure15,
            model.strMeasure16,
            model.strMeasure17,
            model.strMeasure18,
            model.strMeasure19,
            model.strMeasure20
            )

    }

    override fun mapToModel(domain: FoodDetail): FoodDetailItemResponse {
        return FoodDetailItemResponse(
            domain.dateModified,
            domain.idMeal,
            domain.strCategory,
            domain.strMealThumb,
            domain.strArea,
            domain.strCreativeCommonsConfirmed,
            domain.strImageSource,
            domain.strInstructions,
            domain.strTags,
            domain.strYoutube,
            domain.strDrinkAlternate,
            domain.strSource,
            domain.strMeal,

            domain.strIngredient1,
            domain.strIngredient2,
            domain.strIngredient3,
            domain.strIngredient4,
            domain.strIngredient5,
            domain.strIngredient6,
            domain.strIngredient7,
            domain.strIngredient8,
            domain.strIngredient9,
            domain.strIngredient10,
            domain.strIngredient11,
            domain.strIngredient12,
            domain.strIngredient13,
            domain.strIngredient14,
            domain.strIngredient15,
            domain.strIngredient16,
            domain.strIngredient17,
            domain.strIngredient18,
            domain.strIngredient19,
            domain.strIngredient20,

            domain.strMeasure1,
            domain.strMeasure2,
            domain.strMeasure3,
            domain.strMeasure4,
            domain.strMeasure5,
            domain.strMeasure6,
            domain.strMeasure7,
            domain.strMeasure8,
            domain.strMeasure9,
            domain.strMeasure10,
            domain.strMeasure11,
            domain.strMeasure12,
            domain.strMeasure13,
            domain.strMeasure14,
            domain.strMeasure15,
            domain.strMeasure16,
            domain.strMeasure17,
            domain.strMeasure18,
            domain.strMeasure19,
            domain.strMeasure20,
        )
    }
}